secretaria/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf.urls.static import static

import sistema.views
from secretaria import settings

urlpatterns = [
    path('', login_required(sistema.views.SistemaHome.as_view()), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sistema/', include('sistema.urls')),
    path('ticket/', include('ticket.urls')),
    path('general/', include('general.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('TicketHome', login_required(views.TicketHome.as_view()), name="TicketHome"),
    path('TicketHome/<int:opcion>/', login_required(views.TicketHome.as_view()), name="TicketHome"),
    path('TicketHomeGestion/', login_required(views.TicketHomeGestion.as_view()), name="TicketHomeGestionNoID"),
    path('TicketHomeGestion/<int:opcion>/', login_required(views.TicketHomeGestion.as_view()), name="TicketHomeGestion"),
    path('TicketNuevoPub', views.TicketNuevoPub.as_view(), name="TicketNuevoPub"),
    path('TicketDetalle', login_required(views.TicketDetalle.as_view()), name="TicketDetalle"),
    path('TicketTrabajar/<int:ticket>/', login_required(views.TicketTrabajar.as_view()), name="TicketTrabajar"),
    path('TickeTrasferir', login_required(views.TickeTrasferir.as_view()), name="TickeTrasferir"),
    path('TicketResumen/<int:ticket>/', login_required(views.TicketResumen.as_view()), name="TicketResumen"),
]

sistema/models.py
from django.contrib.auth.models import Group, User
from django.db import models

# Create your models here.

Group.add_to_class('home', models.CharField(max_length=150, null=True, blank=True, verbose_name="Home"))
Group.add_to_class('icon', models.CharField(max_length=150, null=True, blank=True, verbose_name="Icono"))

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto = models.ImageField(null=True, blank=True, upload_to='sistema/profile_images')
    tipoUsuario = models.CharField(max_length=20, null=True, blank=True, choices=(
        ('Interno', 'Interno'),
        ('Externo', 'Externo'),
    ), verbose_name='Tipo Usuario', default='Interno')
    area = models.ForeignKey('general.area', verbose_name='Area', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class MenuGrupo(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE)
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    icon = models.CharField(max_length=150, null=True, blank=True, verbose_name="Icono")

    def __str__(self):
        return self.grupo.name + ' ' + self.nombre


class Ayuda(models.Model):
    grupo = models.ForeignKey(Group, verbose_name='Grupo', on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=150, null=True, blank=True, verbose_name="nombre")
    descripcion = models.CharField(max_length=10000, null=True, blank=True, verbose_name="Descripción")
    url = models.CharField(max_length=150, null=True, blank=True, verbose_name="url")
    icon = models.CharField(max_length=150, null=True, blank=True, verbose_name="Icono")

    def __str__(self):
        return self.nombre

templates/menu.html
                <div class="side-menu__content h-full box bg-white/[0.95] rounded-none xl:rounded-xl z-20 relative w-[275px] duration-300 transition-[width] group-[.side-menu--collapsed]:xl:w-[91px] group-[.side-menu--collapsed.side-menu--on-hover]:xl:shadow-[6px_0_12px_-4px_#0000000f] group-[.side-menu--collapsed.side-menu--on-hover]:xl:w-[275px] overflow-hidden flex flex-col">
                    <div class="flex-none hidden xl:flex items-center z-10 px-5 h-[65px] w-[275px] overflow-hidden relative duration-300 group-[.side-menu--collapsed]:xl:w-[91px] group-[.side-menu--collapsed.side-menu--on-hover]:xl:w-[275px]">
                        <a class="flex items-center transition-[margin] duration-300 group-[.side-menu--collapsed.side-menu--on-hover]:xl:ml-0 group-[.side-menu--collapsed]:xl:ml-2" href="">
                            <div class="flex h-[34px] w-[34px] items-center justify-center rounded-lg bg-gradient-to-b from-theme-1 to-theme-2/80 transition-transform ease-in-out group-[.side-menu--collapsed.side-menu--on-hover]:xl:-rotate-180">
                                <div class="relative h-[16px] w-[16px] -rotate-45 [&_div]:bg-white">
                                    <div class="absolute inset-y-0 left-0 my-auto h-[75%] w-[21%] rounded-full opacity-50">
                                    </div>
                                    <div class="absolute inset-0 m-auto h-[120%] w-[21%] rounded-full"></div>
                                    <div class="absolute inset-y-0 right-0 my-auto h-[75%] w-[21%] rounded-full opacity-50">
                                    </div>
                                </div>
                            </div>
                            <!-- Inicio Texto Titulo (Barra de menu lateral izquierda) -->
                            <div class="ml-3.5 font-medium transition-opacity group-[.side-menu--collapsed.side-menu--on-hover]:xl:opacity-100 group-[.side-menu--collapsed]:xl:opacity-0">
                                Hacienda
                            </div>
                        </a>
                        <a class="toggle-compact-menu ml-auto hidden h-[20px] w-[20px] items-center justify-center rounded-full border border-slate-600/40 transition-[opacity,transform] hover:bg-slate-600/5 group-[.side-menu--collapsed]:xl:rotate-180 group-[.side-menu--collapsed.side-menu--on-hover]:xl:opacity-100 group-[.side-menu--collapsed]:xl:opacity-0 3xl:flex" href="">
                            <i data-tw-merge="" data-lucide="arrow-left" class="h-3.5 w-3.5 stroke-[1.3]"></i>
                        </a>
                    </div>
                    <!-- BEGIN: MENU LATERAL IZQUIERDO -->
                    <div class="scrollable-ref w-full h-full z-20 px-5 overflow-y-auto overflow-x-hidden pb-3 [-webkit-mask-image:-webkit-linear-gradient(top,rgba(0,0,0,0),black_30px)] [&:-webkit-scrollbar]:w-0 [&:-webkit-scrollbar]:bg-transparent [&_.simplebar-content]:p-0 [&_.simplebar-track.simplebar-vertical]:w-[10px] [&_.simplebar-track.simplebar-vertical]:mr-0.5 [&_.simplebar-track.simplebar-vertical_.simplebar-scrollbar]:before:bg-slate-400/30">
                        <ul class="scrollable">
                            {% for grupo in user.groups.all %}
                            <li class="side-menu__divider">
                                {{ grupo|upper }}
                            </li>
                                {% for menu in grupo.menugrupo_set.all %}
                                    <li>
                                        <a href="{{ menu.url }}" class="side-menu__link side-menu__link--active ">
                                            <i data-tw-merge="" data-lucide="{{ menu.icon }}" class="stroke-[1] w-5 h-5 side-menu__link__icon"></i>
                                            <div class="side-menu__link__title">{{ menu.nombre }}</div>
                                        </a>
                                        <!-- BEGIN: Second Child -->
                                        <!-- END: Second Child -->
                                    </li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- FIN: MENU LATERAL IZQUIERDO -->
                </div>